import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/provider/theme-provider";
import { Header } from "@/components/header";
import { LenisScroller } from "@/utils/lenis-scroller";

const hevaria = localFont({
  src: [
    {
      path: "../../public/fonts/Heveria-Medium-Trial-BF66b193b1d1fb0.otf",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-hevaria",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${hevaria.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange={false}
        >
          <Header />
          <LenisScroller />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
